subjects = [
    "Barack Obama",
    "Donald Trump",
    "Elon Musk",
    "Taylor Swift",
    "The Rock",
    "Cristiano Ronaldo",
    "Lionel Messi",
    "Narendra Modi",
    "Rahul Gandhi",
    "Amit Shah",
    "Arvind Kejriwal",
    "Virat Kohli",
    "Rohit Sharma",
    "MS Dhoni",
    "Sachin Tendulkar",
    "Jasprit Bumrah",
    "Hardik Pandya",
    "Ravindra Jadeja",
    "Shah Rukh Khan",
    "Salman Khan",
    "Aamir Khan",
    "Ranbir Kapoor",
    "Allu Arjun",
    "Prabhas",
    "Rajinikanth",
    "Deepika Padukone",
    "Alia Bhatt",
    "Priyanka Chopra",
    "A talking squirrel",
    "A confused pigeon",
    "Your neighbour",
    "A chaiwala",
    "An engineering student",
    "A sleepy software developer",
    "An angry auto driver"
]

templates = [
    "{subject} was spotted with {object} in {location}, {connector}.",
    "{subject} secretly revealed {object} at {location}, {connector}.",
    "{subject} accidentally invented {object} in {location}, {connector}.",
    "{subject} launched {object} from {location}, {connector}.",
    "{subject} found {object} in {location}, {connector}.",
    "{subject} forgot {object} at {location}, {connector}.",
    "{subject} bought {object} from {location}, {connector}.",
    "{subject} sold {object} in {location}, {connector}.",
    "{subject} challenged everyone to use {object} in {location}, {connector}.",
    "{subject} announced free {object} for everyone in {location}, {connector}.",
    "{subject} claimed {object} was discovered in {location}, {connector}.",
    "{subject} was caught hiding {object} inside {location}, {connector}.",
    "{subject} accidentally delivered {object} to {location}, {connector}.",
    "{subject} started a business selling {object} in {location}, {connector}.",
    "{subject} used {object} to solve traffic in {location}, {connector}.",
    "{subject} gifted {object} to everyone in {location}, {connector}.",
    "{subject} lost {object} somewhere near {location}, {connector}.",
    "{subject} was seen dancing with {object} at {location}, {connector}.",
    "{subject} claims {object} will change the future of India, {connector}.",
    "{subject} challenged aliens using {object} near {location}, {connector}."
]

objects = [
    "a talking dog",
    "a magical cricket bat",
    "anti-gravity socks",
    "a lifetime supply of pani puri",
    "unlimited biryani",
    "a giant samosa",
    "an invisible auto rickshaw",
    "a time machine",
    "an AI-powered cow",
    "a flying elephant",
    "a robot chaiwala",
    "the world's biggest dosa",
    "a secret Bollywood script",
    "a portal to Mars",
    "a WiFi-powered umbrella",
    "a golden vada pav",
    "a self-driving tractor",
    "a dinosaur",
    "a UFO",
    "a talking buffalo"
]

locations = [
    "Mumbai",
    "Delhi",
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Goa",
    "the Taj Mahal",
    "the Red Fort",
    "Parliament",
    "ISRO Headquarters",
    "an IPL stadium",
    "a roadside chai stall",
    "a metro station",
    "the Himalayas",
    "the Moon",
    "Mars",
    "a shopping mall",
    "a railway station",
    "an engineering college",
    "a movie theatre"
]

connectors = [
    "leaving everyone speechless",
    "making memes go viral",
    "confusing scientists",
    "breaking the internet",
    "according to unverified sources",
    "and nobody knows why",
    "forcing people to question reality",
    "creating nationwide confusion",
    "starting a new internet trend",
    "while everyone watched in disbelief"
]